language: node_js

node_js:
  - '6.9.2'

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

env:
  - TRAVIS=travis CXX=g++-4.8

services:
  - mysql

before_install:
  - cp ./database/config.travis.js ./database/config.js
  - mysql -e 'CREATE DATABASE IF NOT EXISTS sep_test;'

install:
  - npm install

test:
  adapter: mysql2
  database: sep_test
  username: travis
  encoding: utf8

script:
    - npm test
